src/objects/Job_Recurrence_Schedule__c.object
<CustomObject>
    <label>Job Recurrence Schedule</label>
    <nameField>
        <displayFormat>JRS-{00000}</displayFormat>
        <label>JRS ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Recurrence Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Days_of_Week__c</fullName>
        <label>Days of Week</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sunday</fullName>
                </value>
                <value>
                    <fullName>Monday</fullName>
                </value>
                <value>
                    <fullName>Tuesday</fullName>
                </value>
                <value>
                    <fullName>Wednesday</fullName>
                </value>
                <value>
                    <fullName>Thursday</fullName>
                </value>
                <value>
                    <fullName>Friday</fullName>
                </value>
                <value>
                    <fullName>Saturday</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Enter any text that you&apos;d like V4S to copy to the Description field of all Shift records created by this Job Recurrence Schedule.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Desired_Number_of_Volunteers__c</fullName>
        <label>Desired Number of Volunteers</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_End_Date__c</fullName>
        <label>Schedule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Date_Time__c</fullName>
        <label>Schedule Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <inlineHelpText>The Volunteer Job this Recurrence Schedule should be associated with.</inlineHelpText>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipName>Volunteer_Job_Recurrence_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Weekly_Occurrence__c</fullName>
        <label>Weekly Occurrence</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Every</fullName>
                </value>
                <value>
                    <fullName>Alternate</fullName>
                </value>
                <value>
                    <fullName>1st</fullName>
                </value>
                <value>
                    <fullName>2nd</fullName>
                </value>
                <value>
                    <fullName>3rd</fullName>
                </value>
                <value>
                    <fullName>4th</fullName>
                </value>
                <value>
                    <fullName>5th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Volunteer_Hours__c.object
<CustomObject>
    <label>Volunteer Hours</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>HoursID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Volunteers__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Defaults to 1. Increase if this person is bringing additional people whom you are not directly tracking as contacts, and won&apos;t be logging individual volunteer hours against.</inlineHelpText>
        <label>Number of Volunteers</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date_Time__c</fullName>
        <inlineHelpText>The date and time the Volunteer is planning to start working.</inlineHelpText>
        <label>Planned Start Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>No-Show</fullName>
                </value>
                <value>
                    <fullName>Web Sign Up</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Note__c</fullName>
        <inlineHelpText>Notes generated from the system scheduler.</inlineHelpText>
        <label>System Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer_Shift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Shift</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Volunteer_Shift__c.Volunteer_Job__c</field>
                <operation>equals</operation>
                <valueField>$Source.Volunteer_Job__c</valueField>
            </filterItems>
            <infoMessage>You can only pick a Shift that is associated with the current Job.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Volunteer_Shift__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Volunteer_Job__c.object
<CustomObject>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Volunteer Jobs</relationshipLabel>
        <relationshipName>Volunteer_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Number_of_Volunteers__c</fullName>
        <inlineHelpText>The total number of volunteers for this Job who have at least one Volunteer Hours record with a status of either Completed or Confirmed.</inlineHelpText>
        <label>Number of Volunteers</label>
        <summarizedField>Volunteer_Hours__c.Number_of_Volunteers__c</summarizedField>
        <summaryFilterItems>
            <field>Volunteer_Hours__c.Status__c</field>
            <operation>equals</operation>
            <value>Confirmed, Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Volunteer_Hours__c.Volunteer_Job__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

src/objects/Volunteer_Shift__c.object
<CustomObject>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>ShiftID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Desired_Number_of_Volunteers__c</fullName>
        <label>Desired # of Volunteers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>The length of this Shift (in hours).</inlineHelpText>
        <label>Duration (Hours)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Recurrence_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Automatically set by the system scheduler to show the Job Recurrence Schedule this Shift is associated with.</inlineHelpText>
        <label>Job Recurrence Schedule</label>
        <referenceTo>Job_Recurrence_Schedule__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Shifts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>System_Note__c</fullName>
        <inlineHelpText>Notes generated by the system scheduler.</inlineHelpText>
        <label>System Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Job_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
</CustomObject>

src/classes/VOL_JRS_TEST.cls
/**
    Copyright (c) 2016, Salesforce.org
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
**/

@IsTest
private with sharing class VOL_JRS_TEST {
    //******************************************************************************************************
    // Test Job Recurrence Schedules
    @IsTest
    private static void testJRS() {
        // create test data
        Campaign cmp = new Campaign(
            recordtypeid = VOL_SharedCode.recordtypeIdVolunteersCampaign,
            name = 'Job Calendar Test Campaign',
            IsActive = true
        );
        insert cmp;
        Volunteer_Job__c job = new Volunteer_Job__c(name = 'Job1', campaign__c = cmp.Id);
        insert job;
        Volunteer_Shift__c shift = new Volunteer_Shift__c(
            Volunteer_Job__c = job.Id,
            Duration__c = 1,
            Start_Date_Time__c = date.newInstance(2012, 1, 1)
        ); // 1/1/2012 was a Sunday
        insert shift;
        Job_Recurrence_Schedule__c jrs = new Job_Recurrence_Schedule__c(Volunteer_Job__c = job.Id);
        jrs.Days_of_Week__c = 'Monday;Wednesday;Friday';
        jrs.Duration__c = 1;

        jrs.Schedule_Start_Date_Time__c = date.newInstance(2012, 1, 1);
        jrs.Weekly_Occurrence__c = 'Every';
        jrs.Desired_Number_of_Volunteers__c = 5;
        insert jrs;

        // test Day of Week
        Boolean isSun = VOL_JRS.isSundayFirstOfWeek();
        System.assertEquals(isSun ? 1 : 7, VOL_JRS.nDayOfWeek(date.valueOf('2012-1-1')));
        System.assertEquals(isSun ? 7 : 6, VOL_JRS.nDayOfWeek(date.valueOf('2012-1-7')));
        System.assertEquals(isSun ? 3 : 2, VOL_JRS.nDayOfWeek(date.valueOf('2012-1-31')));
        System.assertEquals(isSun ? 4 : 3, VOL_JRS.nDayOfWeek(date.valueOf('2012-2-1')));
        System.assertEquals(isSun ? 4 : 3, VOL_JRS.nDayOfWeek(date.valueOf('2012-2-29')));

        // test dtNthDay
        System.assertEquals(Date.today(), VOL_JRS.dtNthDay(2012, 1, 1, 1));

        // test Every week.
        Date dtNext = VOL_JRS.dtNextDateforJRS(jrs, date.valueOf(shift.Start_Date_Time__c));
        System.assertEquals(1, VOL_JRS.cWeeksNext(jrs, dtNext, false));
        System.assertEquals(date.valueOf('2012-1-2'), dtNext);
        dtNext = VOL_JRS.dtNextDateforJRS(jrs, dtNext);
        System.assertEquals(date.valueOf('2012-1-4'), dtNext);
        dtNext = VOL_JRS.dtNextDateforJRS(jrs, dtNext);
        System.assertEquals(date.valueOf('2012-1-6'), dtNext);
        dtNext = VOL_JRS.dtNextDateforJRS(jrs, dtNext);
        System.assertEquals(date.valueOf('2012-1-9'), dtNext);

        // test Alternate weeks.
        jrs.Weekly_Occurrence__c = 'Alternate';
        update jrs;
        System.assertEquals(2, VOL_JRS.cWeeksNext(jrs, dtNext, true));
        dtNext = VOL_JRS.dtNextDateforJRS(jrs, dtNext);
        System.assertEquals(date.valueOf('2012-1-11'), dtNext);
        dtNext = VOL_JRS.dtNextDateforJRS(jrs, dtNext);
        System.assertEquals(date.valueOf('2012-1-13'), dtNext);
        dtNext = VOL_JRS.dtNextDateforJRS(jrs, dtNext);
        System.assertEquals(date.valueOf('2012-1-23'), dtNext);

        // test figuring out occurrence of day in month
        System.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-1-1')));
        System.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-1-7')));
        System.assertEquals(2, VOL_JRS.nWeekOfDate(date.valueOf('2012-1-8')));
        System.assertEquals(5, VOL_JRS.nWeekOfDate(date.valueOf('2012-1-29')));
        System.assertEquals(5, VOL_JRS.nWeekOfDate(date.valueOf('2012-1-31')));
        System.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-2-1')));
        System.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-2-4')));
        System.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-2-5')));
        System.assertEquals(5, VOL_JRS.nWeekOfDate(date.valueOf('2012-2-29')));
        System.assertEquals(1, VOL_JRS.nWeekOfDate(date.valueOf('2012-2-6')));

        // test Nth week of Month
        jrs.Weekly_Occurrence__c = '3rd';
        update jrs;
        List<Boolean> listWhichWeeks = VOL_JRS.WhichWeeksJRS(jrs);
        System.assertEquals(false, listWhichWeeks[0]);
        System.assertEquals(false, listWhichWeeks[1]);
        System.assertEquals(false, listWhichWeeks[2]);
        System.assertEquals(true, listWhichWeeks[3]);
        System.assertEquals(false, listWhichWeeks[4]);
        System.assertEquals(false, listWhichWeeks[5]);

        System.assertEquals(2, VOL_JRS.cWeeksNext(jrs, date.valueOf('2012-1-1'), false));
        System.assertEquals(2, VOL_JRS.cWeeksNext(jrs, date.valueOf('2012-1-7'), false));
        System.assertEquals(1, VOL_JRS.cWeeksNext(jrs, date.valueOf('2012-1-8'), false));
        System.assertEquals(1, VOL_JRS.cWeeksNext(jrs, date.valueOf('2012-1-14'), false));
        System.assertEquals(5, VOL_JRS.cWeeksNext(jrs, date.valueOf('2012-1-15'), false));

        dtNext = VOL_JRS.dtNextDateforJRS(jrs, date.valueOf('2012-1-7'));
        System.assertEquals(date.valueOf('2012-1-16'), dtNext);

        jrs.Days_of_Week__c = 'Monday';
        update jrs;
        dtNext = VOL_JRS.dtNextDateforJRS(jrs, date.valueOf('2012-4-16'));
        System.assertEquals(date.valueOf('2012-5-21'), dtNext);

        jrs.Days_of_Week__c = 'Wednesday';
        update jrs;
        dtNext = VOL_JRS.dtNextDateforJRS(jrs, date.valueOf('2012-4-18'));
        System.assertEquals(date.valueOf('2012-5-16'), dtNext);

        jrs.Weekly_Occurrence__c = '1st';
        jrs.Days_of_Week__c = 'Monday';
        update jrs;
        dtNext = VOL_JRS.dtNextDateforJRS(jrs, date.valueOf('2012-2-6'));
        System.assertEquals(date.valueOf('2012-3-5'), dtNext);

        jrs.Weekly_Occurrence__c = '2nd;4th;';
        jrs.Days_of_Week__c = 'Sunday';
        update jrs;
        dtNext = VOL_JRS.dtNextDateforJRS(jrs, date.valueOf('2012-8-1'));
        System.assertEquals(date.valueOf('2012-8-12'), dtNext);

        // test batch calculations
        VOL_BATCH_Recurrence r = new VOL_BATCH_Recurrence();
        r.execute(null);

        // test deleting the JRS
        List<Volunteer_Shift__c> listShift = [
            SELECT Id, Name
            FROM Volunteer_Shift__c
            WHERE Job_Recurrence_Schedule__c = :jrs.Id
        ];
        System.assert(listShift.size() > 0);
        delete jrs;
        listShift = [SELECT Id, Name FROM Volunteer_Shift__c WHERE Job_Recurrence_Schedule__c = :jrs.Id];
        System.assertEquals(0, listShift.size());
    }

    //******************************************************************************************************
    // test that modifying a JRS reuses already existing Shifts
    @IsTest
    private static void testJRSShiftReuse() {
        // create test data
        Campaign cmp = new Campaign(
            recordtypeid = VOL_SharedCode.recordtypeIdVolunteersCampaign,
            name = 'Job Calendar Test Campaign',
            IsActive = true
        );
        insert cmp;
        Volunteer_Job__c job = new Volunteer_Job__c(name = 'Job1', campaign__c = cmp.Id);
        insert job;
        Job_Recurrence_Schedule__c jrs = new Job_Recurrence_Schedule__c(Volunteer_Job__c = job.Id);
        jrs.Days_of_Week__c = 'Monday';
        jrs.Duration__c = 1;
        jrs.Schedule_Start_Date_Time__c = System.now();
        jrs.Weekly_Occurrence__c = 'Every';
        jrs.Desired_Number_of_Volunteers__c = 5;
        jrs.Description__c = 'initial description';
        insert jrs;

        List<Volunteer_Shift__c> listShift = [SELECT Id FROM Volunteer_Shift__c];
        Set<Id> setShiftId = new Set<Id>();
        for (Volunteer_Shift__c shift : listShift) {
            setShiftId.add(shift.Id);
        }
        Integer cShifts = setShiftId.size();
        System.assert(cShifts > 0);

        // now modify the JRS
        jrs.Days_of_Week__c = 'Monday;Tuesday';
        jrs.Description__c = 'new description';
        Test.startTest();
        update jrs;
        Test.stopTest();

        listShift = [SELECT Id, CreatedDate, LastModifiedDate, Description__c FROM Volunteer_Shift__c];
        Integer cShiftsInitial = 0;
        Integer cShiftsNew = 0;
        for (Volunteer_Shift__c shift : listShift) {
            if (setShiftId.contains(shift.Id)) {
                cShiftsInitial++;
            } else {
                cShiftsNew++;
            }
            System.assertEquals('new description', shift.Description__c);
        }
        System.assertEquals(cShifts, cShiftsInitial);
        System.assert(cShifts == cShiftsNew || cShifts == cShiftsNew - 1 || cShifts == cShiftsNew + 1);
    }

    //******************************************************************************************************
    // test that modifying a JRS deletes already existing Shifts that no longer match the JRS
    @IsTest
    private static void testJRSShiftDelete() {
        // create test data
        Campaign cmp = new Campaign(
            recordtypeid = VOL_SharedCode.recordtypeIdVolunteersCampaign,
            name = 'Job Calendar Test Campaign',
            IsActive = true
        );
        insert cmp;
        Volunteer_Job__c job = new Volunteer_Job__c(name = 'Job1', campaign__c = cmp.Id);
        insert job;
        Job_Recurrence_Schedule__c jrs = new Job_Recurrence_Schedule__c(Volunteer_Job__c = job.Id);
        jrs.Days_of_Week__c = 'Monday';
        jrs.Duration__c = 1;
        jrs.Schedule_Start_Date_Time__c = System.now();
        jrs.Weekly_Occurrence__c = 'Every';
        jrs.Desired_Number_of_Volunteers__c = 5;
        jrs.Description__c = 'initial description';
        insert jrs;

        List<Volunteer_Shift__c> listShift = [SELECT Id FROM Volunteer_Shift__c];
        Set<Id> setShiftId = new Set<Id>();
        for (Volunteer_Shift__c shift : listShift) {
            setShiftId.add(shift.Id);
        }
        Integer cShifts = setShiftId.size();
        System.assert(cShifts > 0);

        // now modify the JRS
        jrs.Days_of_Week__c = 'Tuesday';
        jrs.Description__c = 'new description';
        Test.startTest();
        update jrs;
        Test.stopTest();

        listShift = [SELECT Id, CreatedDate, LastModifiedDate, Description__c FROM Volunteer_Shift__c];
        Integer cShiftsInitial = 0;
        Integer cShiftsNew = 0;
        for (Volunteer_Shift__c shift : listShift) {
            if (setShiftId.contains(shift.Id)) {
                cShiftsInitial++;
            } else {
                cShiftsNew++;
            }
            System.assertEquals('new description', shift.Description__c);
        }
        System.assertEquals(0, cShiftsInitial);
        System.assert(cShifts == cShiftsNew || cShifts == cShiftsNew - 1 || cShifts == cShiftsNew + 1);
    }

    //******************************************************************************************************
    // test that deleting a JRS deletes Shifts with no Hours, and just detaches Shifts with Hours.
    @IsTest
    private static void testJRSDelete() {
        // create test data
        Account acc = new Account(name = 'account1');
        insert acc;
        Contact con = new Contact(Lastname = 'foo', AccountId = acc.Id);
        insert con;
        Campaign cmp = new Campaign(
            recordtypeid = VOL_SharedCode.recordtypeIdVolunteersCampaign,
            name = 'Job Calendar Test Campaign',
            IsActive = true
        );
        insert cmp;
        Volunteer_Job__c job = new Volunteer_Job__c(name = 'Job1', campaign__c = cmp.Id);
        insert job;
        Job_Recurrence_Schedule__c jrs = new Job_Recurrence_Schedule__c(Volunteer_Job__c = job.Id);
        jrs.Days_of_Week__c = 'Monday';
        jrs.Duration__c = 1;
        jrs.Schedule_Start_Date_Time__c = System.today().addMonths(-1).toStartOfMonth();
        jrs.Schedule_End_Date__c = System.today().addmonths(2).toStartOfMonth().addDays(-1);
        jrs.Weekly_Occurrence__c = 'Every';
        jrs.Desired_Number_of_Volunteers__c = 5;
        jrs.Description__c = 'initial description';
        insert jrs;

        List<Volunteer_Shift__c> listShift = [SELECT Id, Volunteer_Job__c, Start_Date_Time__c FROM Volunteer_Shift__c];
        Integer countTotalShifts = listShift.size();
        System.assert(countTotalShifts >= 12); // we should get at least 4 Mondays each month.

        // now create Hours for half the shifts
        List<Volunteer_Hours__c> listHours = new List<Volunteer_Hours__c>();
        Integer countShiftsWithHours = 0;
        for (Integer i = 0; i < listShift.size(); i++) {
            if (Math.mod(i, 2) == 0) {
                Volunteer_Shift__c shift = listShift[i];
                countShiftsWithHours++;
                Integer cHoursLDV = 1;
                // for the first shift, we create a bunch of hours, to ensure our delete handler uses soql-for-loops
                // on the subquery it uses!
                if (countShiftsWithHours == 1) {
                    cHoursLDV = 2000;
                }
                for (Integer j = 0; j < cHoursLDV; j++) {
                    Volunteer_Hours__c hr = new Volunteer_Hours__c(
                        Contact__c = con.Id,
                        Volunteer_Job__c = shift.Volunteer_Job__c,
                        Volunteer_Shift__c = shift.Id,
                        Status__c = 'Prospect',
                        Start_Date__c = shift.Start_Date_Time__c.Date(),
                        Planned_Start_Date_Time__c = shift.Start_Date_Time__c,
                        Hours_Worked__c = 0,
                        Number_Of_Volunteers__c = 0
                    );
                    listHours.add(hr);
                }
            }
        }
        System.assert(countTotalShifts > countShiftsWithHours);
        insert listHours;

        Test.startTest();
        delete jrs;
        Test.stopTest();

        // verify some Shifts deleted and some detached
        listShift = [
            SELECT Id, Volunteer_Job__c, Start_Date_Time__c, Job_Recurrence_Schedule__c, System_Note__c
            FROM Volunteer_Shift__c
        ];
        System.assertEquals(countShiftsWithHours, listShift.size());
        for (Volunteer_Shift__c shift : listShift) {
            System.assertEquals(null, shift.Job_Recurrence_Schedule__c);
            System.assert(shift.System_Note__c.contains(Label.labelJRSShiftRemovedSystemNote));
        }
    }
    //******************************************************************************************************
    // test that updating a JRS deletes Shifts with no Hours, and just detaches Shifts with Hours.
    @IsTest
    private static void testJRSUpdate() {
        // create test data
        Account acc = new Account(name = 'account1');
        insert acc;
        Contact con = new Contact(Lastname = 'foo', AccountId = acc.Id);
        insert con;
        Campaign cmp = new Campaign(
            recordtypeid = VOL_SharedCode.recordtypeIdVolunteersCampaign,
            name = 'Job Calendar Test Campaign',
            IsActive = true
        );
        insert cmp;
        Volunteer_Job__c job = new Volunteer_Job__c(name = 'Job1', campaign__c = cmp.Id);
        insert job;
        Job_Recurrence_Schedule__c jrs = new Job_Recurrence_Schedule__c(Volunteer_Job__c = job.Id);
        jrs.Days_of_Week__c = 'Monday;Wednesday';
        jrs.Duration__c = 1;
        jrs.Schedule_Start_Date_Time__c = System.today().addMonths(-1).toStartOfMonth();
        jrs.Schedule_End_Date__c = System.today().addmonths(2).toStartOfMonth().addDays(-1);
        jrs.Weekly_Occurrence__c = 'Every';
        jrs.Desired_Number_of_Volunteers__c = 5;
        jrs.Description__c = 'initial description';
        insert jrs;

        List<Volunteer_Shift__c> listShift = [SELECT Id, Volunteer_Job__c, Start_Date_Time__c FROM Volunteer_Shift__c];
        Integer countTotalShifts = listShift.size();
        System.assert(countTotalShifts >= 24); // we should get at least 4 Mondays & Wednesdays each month.

        // now create Hours for half the shifts
        List<Volunteer_Hours__c> listHours = new List<Volunteer_Hours__c>();
        Integer countShiftsWithHours = 0;
        for (Integer i = 0; i < listShift.size(); i++) {
            if (Math.mod(i, 3) == 0) {
                Volunteer_Shift__c shift = listShift[i];
                countShiftsWithHours++;
                Integer cHoursLDV = 1;
                // for the first shift, we create a bunch of hours, to ensure our delete handler uses soql-for-loops
                // on the subquery it uses!
                if (countShiftsWithHours == 1) {
                    cHoursLDV = 2000;
                }
                for (Integer j = 0; j < cHoursLDV; j++) {
                    Volunteer_Hours__c hr = new Volunteer_Hours__c(
                        Contact__c = con.Id,
                        Volunteer_Job__c = shift.Volunteer_Job__c,
                        Volunteer_Shift__c = shift.Id,
                        Status__c = 'Prospect',
                        Start_Date__c = shift.Start_Date_Time__c.Date(),
                        Planned_Start_Date_Time__c = shift.Start_Date_Time__c,
                        Hours_Worked__c = 0,
                        Number_Of_Volunteers__c = 0
                    );
                    listHours.add(hr);
                }
            }
        }
        System.assert(countTotalShifts > countShiftsWithHours);
        insert listHours;

        Test.startTest();
        jrs.Days_of_Week__c = 'Monday;Friday';
        update jrs;
        Test.stopTest();

        // verify some Shifts deleted and some detached
        listShift = [
            SELECT Id, Volunteer_Job__c, Start_Date_Time__c, Job_Recurrence_Schedule__c, System_Note__c
            FROM Volunteer_Shift__c
            WHERE Job_Recurrence_Schedule__c = NULL
        ];
        System.assert(listShift.size() > 0);
        for (Volunteer_Shift__c shift : listShift) {
            System.assertEquals(null, shift.Job_Recurrence_Schedule__c);
            System.assert(shift.System_Note__c.contains(Label.labelJRSShiftRemovedSystemNote));
        }
    }
}